/*!
\file dtype.c
\author Edward Ji
\date 27 Jul 2022

\brief
A demonstration of the utilities generated by `dtype.h`.

\stdout
```
3.1415 2.7182 1.618
```
*/

#include "../darray.h"
#include "../util/dtype.h"

MAKE_DTYPE_DOUBLE()

int main() {
    darray *numbers = new_darray(free);

    /*!
     * The `new_double` function allocates a new double on the heap with
     * provided value.
     */
    darray_append(numbers, new_double(3.0000)); // inaccurate pi
    darray_append(numbers, new_double(2.7182)); // e
    darray_append(numbers, new_double(1.6180)); // golden ratio

    /*!
     * The `double_cpy_deep` function returns a deep copy of the given double.
     */
    darray *clone = darray_clone(numbers, double_cpy);
    darray_set_item_free(numbers, NULL);

    /*!
     * The `double_cmp` function complies with the description in `comparator`.
     */
    double inaccurate_pi = 3.0000;
    size_t idx;
    darray_search(clone, &inaccurate_pi, double_cmp, &idx);
    darray_pop(clone, idx);
    darray_insert(clone, idx, new_double(3.1415));

    /*!
     * The `print_double` function prints a given double in a common format.
     */
    darray_foreach(clone, print_double);
    putchar('\n');

    del_darray(numbers);
    del_darray(clone);

    return 0;
}
